spring:
  data:
    mongodb:
      uri: ${com_camenduru_mongodb_uri}

token: ${com_camenduru_discord_token}
type: ${com_camenduru_job_default_type}
result: ${com_camenduru_discord_result}

server:
  port : 8081