spring:
  data:
    mongodb:
      uri: ${com_camenduru_mongodb_uri}

camenduru:
  discord.token: ${com_camenduru_discord_token}
  discord.default.result: ${com_camenduru_discord_default_result}
  discord.default.result.suffix: ${com_camenduru_discord_default_result_suffix}
  discord.default.discord: ${com_camenduru_discord_default_discord}

server:
  port : 8081