spring:
  data:
    mongodb:
      uri: ${com_camenduru_web_data_mongodb_uri}

token: ${com_camenduru_discord_token}
type: ${com_camenduru_discord_type}
result: ${com_camenduru_discord_result}

server:
  port : 8081